### ISSUE TITLE
gitomator-make-teams freaks out if trying to give maintainer role an organization admin

### ISSUE THREAD

**Issue by jmzaleski** [gitomator/gitomator#12]
Happens that Gadal is admin (shouldn't be, but that's another story)

sorry it won't let me attach .yml 

[302-maintainer-issue.zip](https://github.com/gitomator/gitomator/files/752492/302-maintainer-issue.zip)

**Comment by joeyfreund** [comment]
Thanks for reporting.

Just so it's more visible, here's the error (from the log in your attached zip file):

```
E, [2017-02-04T18:49:48.520190 #69] ERROR -- : Cannot create/update Gadal's membership in ItWorkedYesterday - PUT https://api.github.com/teams/2260470/memberships/Gadal: 422 - User is already an admin of this organization, so they can't be promoted to a team maintainer.
Error summary:
  code: already_org_admin
  field: user
  resource: TeamMember // See: https://developer.github.com/v3/orgs/teams/#add-or-update-team-membership.
/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/response.rb:9:in `block in call'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/connection.rb:177:in `put'
	/usr/local/bundle/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/connection.rb:37:in `put'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/client/organizations.rb:537:in `add_team_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/github/hosting_provider.rb:263:in `create_team_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/service.rb:49:in `service_call'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/service/hosting.rb:93:in `create_team_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:51:in `create_or_update_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:28:in `block in run'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:26:in `each'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:26:in `run'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/util/script_util.rb:50:in `run_task'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-teams:17:in `block in <top (required)>'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-teams:16:in `each'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-teams:16:in `<top (required)>'
	/usr/local/bundle/bin/gitomator-make-teams:22:in `load'
	/usr/local/bundle/bin/gitomator-make-teams:22:in `<main>'
I, [2017-02-04T18:49:48.758620 #69]  INFO -- : Creating team: MountBahen
I, [2017-02-04T18:49:49.489932 #69]  INFO -- : Adding ShisunXia to team MountBahen (role: member).
I, [2017-02-04T18:49:49.950047 #69]  INFO -- : Adding c4khatta to team MountBahen (role: member).
I, [2017-02-04T18:49:50.382930 #69]  INFO -- : Adding singhkaran to team MountBahen (role: member).
I, [2017-02-04T18:49:50.825951 #69]  INFO -- : Adding responsive309 to team MountBahen (role: member).
I, [2017-02-04T18:49:51.276991 #69]  INFO -- : Adding Iakis to team MountBahen (role: member).
I, [2017-02-04T18:49:51.792690 #69]  INFO -- : Adding JLyX to team MountBahen (role: member).
I, [2017-02-04T18:49:52.270662 #69]  INFO -- : Adding PhilHernandez to team MountBahen (role: member).
I, [2017-02-04T18:49:52.711119 #69]  INFO -- : Adding Gadal to team MountBahen (role: maintainer).
E, [2017-02-04T18:49:52.966691 #69] ERROR -- : Cannot create/update Gadal's membership in MountBahen - PUT https://api.github.com/teams/2260471/memberships/Gadal: 422 - User is already an admin of this organization, so they can't be promoted to a team maintainer.
Error summary:
  code: already_org_admin
  field: user
  resource: TeamMember // See: https://developer.github.com/v3/orgs/teams/#add-or-update-team-membership.
/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/response.rb:9:in `block in call'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/connection.rb:177:in `put'
	/usr/local/bundle/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/connection.rb:37:in `put'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/client/organizations.rb:537:in `add_team_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/github/hosting_provider.rb:263:in `create_team_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/service.rb:49:in `service_call'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/service/hosting.rb:93:in `create_team_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:51:in `create_or_update_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:28:in `block in run'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:26:in `each'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:26:in `run'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/util/script_util.rb:50:in `run_task'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-teams:17:in `block in <top (required)>'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-teams:16:in `each'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-teams:16:in `<top (required)>'
	/usr/local/bundle/bin/gitomator-make-teams:22:in `load'
	/usr/local/bundle/bin/gitomator-make-teams:22:in `<main>'
I, [2017-02-04T18:49:53.200867 #69]  INFO -- : Creating team: GeninSquad
I, [2017-02-04T18:49:53.914619 #69]  INFO -- : Adding eddiequan to team GeninSquad (role: member).
I, [2017-02-04T18:49:54.354414 #69]  INFO -- : Adding chargadesilva to team GeninSquad (role: member).
I, [2017-02-04T18:49:54.806122 #69]  INFO -- : Adding Lyjame to team GeninSquad (role: member).
I, [2017-02-04T18:49:55.250809 #69]  INFO -- : Adding matt-duell to team GeninSquad (role: member).
I, [2017-02-04T18:49:55.687154 #69]  INFO -- : Adding Aaron-Tang to team GeninSquad (role: member).
I, [2017-02-04T18:49:56.121458 #69]  INFO -- : Adding admiralcoco to team GeninSquad (role: member).
I, [2017-02-04T18:49:56.580641 #69]  INFO -- : Adding tylerpham to team GeninSquad (role: member).
I, [2017-02-04T18:49:57.018386 #69]  INFO -- : Adding garysong23 to team GeninSquad (role: maintainer).
I, [2017-02-04T18:49:57.511232 #69]  INFO -- : Creating team: Awol
I, [2017-02-04T18:49:58.226787 #69]  INFO -- : Adding ChoJohn to team Awol (role: member).
I, [2017-02-04T18:49:58.697933 #69]  INFO -- : Adding racormaz to team Awol (role: member).
I, [2017-02-04T18:49:59.170070 #69]  INFO -- : Adding shreymahendru to team Awol (role: member).
I, [2017-02-04T18:49:59.658713 #69]  INFO -- : Adding TenzinLama to team Awol (role: member).
I, [2017-02-04T18:50:00.155015 #69]  INFO -- : Adding shubDhond to team Awol (role: member).
I, [2017-02-04T18:50:00.605999 #69]  INFO -- : Adding waynellin to team Awol (role: member).
I, [2017-02-04T18:50:01.098385 #69]  INFO -- : Adding davjhan to team Awol (role: member).
I, [2017-02-04T18:50:01.697714 #69]  INFO -- : Adding priyen to team Awol (role: maintainer).
I, [2017-02-04T18:50:02.421811 #69]  INFO -- : Creating team: LemonDudes
I, [2017-02-04T18:50:03.375469 #69]  INFO -- : Adding g3wanghc to team LemonDudes (role: member).
I, [2017-02-04T18:50:03.921848 #69]  INFO -- : Adding freeatnet to team LemonDudes (role: member).
I, [2017-02-04T18:50:04.541586 #69]  INFO -- : Adding sinaghaffari to team LemonDudes (role: member).
I, [2017-02-04T18:50:05.083471 #69]  INFO -- : Adding gohnicho to team LemonDudes (role: member).
I, [2017-02-04T18:50:05.591617 #69]  INFO -- : Adding bountygiver to team LemonDudes (role: member).
I, [2017-02-04T18:50:06.046333 #69]  INFO -- : Adding gomuramatsu to team LemonDudes (role: member).
I, [2017-02-04T18:50:06.681028 #69]  INFO -- : Adding Gadal to team LemonDudes (role: maintainer).
E, [2017-02-04T18:50:06.991851 #69] ERROR -- : Cannot create/update Gadal's membership in LemonDudes - PUT https://api.github.com/teams/2260474/memberships/Gadal: 422 - User is already an admin of this organization, so they can't be promoted to a team maintainer.
Error summary:
  code: already_org_admin
  field: user
  resource: TeamMember // See: https://developer.github.com/v3/orgs/teams/#add-or-update-team-membership.
/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/response.rb:9:in `block in call'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/connection.rb:177:in `put'
	/usr/local/bundle/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/connection.rb:37:in `put'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/client/organizations.rb:537:in `add_team_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/github/hosting_provider.rb:263:in `create_team_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/service.rb:49:in `service_call'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/service/hosting.rb:93:in `create_team_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:51:in `create_or_update_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:28:in `block in run'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:26:in `each'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:26:in `run'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/util/script_util.rb:50:in `run_task'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-teams:17:in `block in <top (required)>'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-teams:16:in `each'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-teams:16:in `<top (required)>'
	/usr/local/bundle/bin/gitomator-make-teams:22:in `load'
	/usr/local/bundle/bin/gitomator-make-teams:22:in `<main>'
I, [2017-02-04T18:50:07.251186 #69]  INFO -- : Creating team: GhostBusters
I, [2017-02-04T18:50:08.101420 #69]  INFO -- : Adding gypsyfeng to team GhostBusters (role: member).
I, [2017-02-04T18:50:08.554901 #69]  INFO -- : Adding marc22alain to team GhostBusters (role: member).
I, [2017-02-04T18:50:09.022516 #69]  INFO -- : Adding JPinkney to team GhostBusters (role: member).
I, [2017-02-04T18:50:09.499593 #69]  INFO -- : Adding Rbandon64sp to team GhostBusters (role: member).
I, [2017-02-04T18:50:09.965734 #69]  INFO -- : Adding aa3993 to team GhostBusters (role: member).
I, [2017-02-04T18:50:10.479449 #69]  INFO -- : Adding garysong23 to team GhostBusters (role: maintainer).
I, [2017-02-04T18:50:10.990804 #69]  INFO -- : Creating team: Enterprise
I, [2017-02-04T18:50:11.732757 #69]  INFO -- : Adding allenaerostar to team Enterprise (role: member).
I, [2017-02-04T18:50:12.271078 #69]  INFO -- : Adding nguyenphillip to team Enterprise (role: member).
I, [2017-02-04T18:50:12.726997 #69]  INFO -- : Adding kevin-kc to team Enterprise (role: member).
I, [2017-02-04T18:50:13.179831 #69]  INFO -- : Adding anders-leung to team Enterprise (role: member).
I, [2017-02-04T18:50:13.626133 #69]  INFO -- : Adding cainky to team Enterprise (role: member).
I, [2017-02-04T18:50:14.087034 #69]  INFO -- : Adding Gadal to team Enterprise (role: maintainer).
E, [2017-02-04T18:50:14.352581 #69] ERROR -- : Cannot create/update Gadal's membership in Enterprise - PUT https://api.github.com/teams/2260476/memberships/Gadal: 422 - User is already an admin of this organization, so they can't be promoted to a team maintainer.
Error summary:
  code: already_org_admin
  field: user
  resource: TeamMember // See: https://developer.github.com/v3/orgs/teams/#add-or-update-team-membership.
/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/response.rb:9:in `block in call'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
	/usr/local/bundle/gems/faraday-0.11.0/lib/faraday/connection.rb:177:in `put'
	/usr/local/bundle/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/connection.rb:37:in `put'
	/usr/local/bundle/gems/octokit-4.6.2/lib/octokit/client/organizations.rb:537:in `add_team_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/github/hosting_provider.rb:263:in `create_team_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/service.rb:49:in `service_call'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/service/hosting.rb:93:in `create_team_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:51:in `create_or_update_membership'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:28:in `block in run'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:26:in `each'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/setup_team.rb:26:in `run'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/util/script_util.rb:50:in `run_task'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-teams:17:in `block in <top (required)>'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-teams:16:in `each'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-teams:16:in `<top (required)>'
	/usr/local/bundle/bin/gitomator-make-teams:22:in `load'
	/usr/local/bundle/bin/gitomator-make-teams:22:in `<main>'
gitomator-image-root@d5e2c583fddd:/gitomator# 
```

**Comment by joeyfreund** [comment]
I'll have to read a little more about why the authors of Octokit chose this behaviour.

I understand that an _organization admin_ already has maintainer permissions for all teams in the organization, but I don't understand why one would throw an error.      
In fact, I can see a case where someone is demoted from an organization admin to a regular member of the organization, yet you still want them to keep their maintainer privileges for some team(s).
